# GoGDBLLM Configuration

server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

llm:
  default_provider: "anthropic"
  default_model: "claude-3-sonnet-20240229"
  # api_key: "" # Uncomment and set your API key here (not recommended) or use environment variable GOGDBLLM_LLM_API_KEY

gdb:
  path: "gdb"
  timeout: 2
  max_processes: 5

logs:
  level: "info"
  directory: "./logs"
  json_format: true

uploads:
  directory: "./uploads"
  max_file_size: 10485760 # 10MB in bytes 